[package]
name = "xlsx_writer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
encoding_rs = "0.8.28"
dirs = "3.0"
chrono = "0.4.23"
rm_rf = "0.6.1"